
export enum TlsRelayConnectionState {
  NEW,
  WAITING_FOR_KEY,
  EXPIRED_WAITING_FOR_KEY,
  KEY_INVALID,
  WAITING_FOR_PEER,
  EXPIRED_WAITING_FOR_PEER,
  NEGOTIATING_CONNECTION,
  DIRECT_CONNECTION,
  RELAYED_CONNECTION,
  BROKEN_RELAY,
}
